brew install --cask deepl
brew install --cask google-chrome 
brew install --cask microsoft-edge
brew install --cask vivaldi
brew install --cask gnuplot
brew install --cask kindle
brew install --cask visual-studio-code
brew install --cask slack
brew install --cask skype
brew install --cask zoom
brew install --cask gfortran
brew install mactex-no-gui --cask